services:
  
  http:
    image: nginx:latest
    container_name: http-container
    ports:
      - 8082:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - ./html:/var/www/html  
    depends_on:
      - script

  
  script:
    build:
      context: .  
    container_name: script-container
    volumes:
      - ./html:/var/www/html
    depends_on:
      - data
  
  data:
    image: mariadb:latest  
    container_name: data-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql  
    ports:
      - "3306:3306"  
